#!/usr/bin/env python3
"""Fetch and generate GNU ld option metadata from binutils sources."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import subprocess
import sys
import tempfile
import time
import tomllib
from pathlib import Path
from urllib.parse import quote
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "option" / "ld" / "manifest.toml"
DEFAULT_OUTPUT_DIR = ROOT / "option" / "ld"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "ld-options"

BINUTILS_REPO_URL = "https://sourceware.org/git/binutils-gdb.git"
BINUTILS_GIT_URL = "https://sourceware.org/git/binutils-gdb.git"
BINUTILS_CGIT_URL = "https://sourceware.org/git/"
LEXSUP_PATH = "ld/lexsup.c"


def run(
    args: list[str],
    *,
    cwd: Path | None = None,
    timeout: int = 300,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=cwd,
        check=True,
        text=True,
        timeout=timeout,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def version_key(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


def major_version(version: str) -> str:
    return version.split(".", 1)[0]


def version_output_path(output_dir: Path, version: str) -> Path:
    return output_dir / major_version(version) / f"{version}.toml"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch_bytes(url: str, timeout: int = 120, attempts: int = 5) -> bytes:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(url, timeout=timeout) as response:
                return response.read()
        except Exception as error:
            last_error = error
            if attempt + 1 == attempts:
                break
            time.sleep(0.5 * (attempt + 1))
    assert last_error is not None
    raise last_error


def source_url(ref: str, path: str) -> str:
    return (
        f"{BINUTILS_CGIT_URL}?p=binutils-gdb.git;a=blob_plain;"
        f"f={quote(path)};hb={quote(ref)}"
    )


def fetch_source(ref: str, path: str, cache_dir: Path) -> tuple[bytes, str]:
    cache_path = cache_dir / "sources" / ref / path
    if cache_path.exists():
        data = cache_path.read_bytes()
        return data, sha256_bytes(data)
    data = fetch_bytes(source_url(ref, path))
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_bytes(data)
    return data, sha256_bytes(data)


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: object) -> str:
    if value is None:
        raise ValueError("TOML does not support null values")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value: {type(value)!r}")


def write_table(lines: list[str], table: dict[str, object]) -> None:
    for key, value in table.items():
        if value is None:
            continue
        if isinstance(value, list) and len(value) == 0:
            lines.append(f"{key} = []")
            continue
        lines.append(f"{key} = {toml_value(value)}")


def normalize_release_version(tag_name: str) -> str | None:
    match = re.fullmatch(r"binutils-(\d+)_(\d+)(?:_([0-9]+(?:\.[0-9]+)?))?", tag_name)
    if match is None:
        return None
    parts = [match.group(1), match.group(2)]
    suffix = match.group(3)
    if suffix is None:
        parts.append("0")
    else:
        parts.extend(suffix.split("."))
    return ".".join(parts)


def write_manifest(path: Path, releases: list[dict[str, str]]) -> None:
    lines = [
        "# Generated by scripts/update_ld_options.py --refresh-manifest.",
        "# Edit only when intentionally changing the pinned source set.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "tool": "ld",
            "implementation": "gnu",
            "source_repo": BINUTILS_REPO_URL,
            "stable_only": True,
            "source_path": LEXSUP_PATH,
        },
    )
    lines.append("")
    for release in releases:
        lines.append("[[releases]]")
        write_table(lines, release)
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def refresh_manifest(path: Path) -> None:
    output = run(
        ["git", "ls-remote", "--tags", BINUTILS_GIT_URL, "refs/tags/binutils-*"],
        timeout=600,
    ).stdout
    tag_refs: dict[str, tuple[str, str]] = {}
    peeled_tag_refs: dict[str, tuple[str, str]] = {}
    for line in output.splitlines():
        sha, ref = line.split("\t", 1)
        if not ref.startswith("refs/tags/"):
            continue
        peeled = ref.endswith("^{}")
        tag = ref.removesuffix("^{}").rsplit("/", 1)[1]
        version = normalize_release_version(tag)
        if version is None:
            continue
        if peeled:
            peeled_tag_refs[version] = (sha, tag)
        else:
            tag_refs[version] = (sha, tag)
    tags = {**tag_refs, **peeled_tag_refs}
    releases = [
        {
            "version": version,
            "tag": tag,
            "commit": commit,
            "source_path": LEXSUP_PATH,
        }
        for version, (commit, tag) in sorted(tags.items(), key=lambda item: version_key(item[0]))
    ]
    write_manifest(path, releases)


def load_manifest(path: Path) -> tuple[dict[str, object], list[dict[str, str]]]:
    with path.open("rb") as file:
        data = tomllib.load(file)
    metadata = data.get("metadata", {})
    releases = data.get("releases", [])
    if not isinstance(metadata, dict) or not isinstance(releases, list):
        raise ValueError(f"invalid manifest shape: {path}")
    return metadata, releases


def strip_c_comments(value: str) -> str:
    result: list[str] = []
    i = 0
    in_string = False
    in_char = False
    escape = False
    while i < len(value):
        ch = value[i]
        nxt = value[i + 1] if i + 1 < len(value) else ""
        if in_string or in_char:
            result.append(ch)
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif in_string and ch == '"':
                in_string = False
            elif in_char and ch == "'":
                in_char = False
            i += 1
            continue
        if ch == '"':
            in_string = True
            result.append(ch)
            i += 1
            continue
        if ch == "'":
            in_char = True
            result.append(ch)
            i += 1
            continue
        if ch == "/" and nxt == "*":
            i += 2
            while i + 1 < len(value) and not (value[i] == "*" and value[i + 1] == "/"):
                if value[i] == "\n":
                    result.append("\n")
                i += 1
            i += 2
            continue
        if ch == "/" and nxt == "/":
            i += 2
            while i < len(value) and value[i] != "\n":
                i += 1
            continue
        result.append(ch)
        i += 1
    return "".join(result)


def find_matching_brace(text: str, open_index: int) -> int:
    depth = 0
    in_string = False
    in_char = False
    escape = False
    for index in range(open_index, len(text)):
        ch = text[index]
        if in_string or in_char:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif in_string and ch == '"':
                in_string = False
            elif in_char and ch == "'":
                in_char = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "'":
            in_char = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unterminated brace block")


def extract_ld_options_table(text: str) -> tuple[str, int]:
    marker = "ld_options[]"
    start = text.find(marker)
    if start == -1:
        raise ValueError("ld_options[] table not found")
    open_index = text.find("{", start)
    if open_index == -1:
        raise ValueError("ld_options[] initializer not found")
    close_index = find_matching_brace(text, open_index)
    line_offset = text.count("\n", 0, open_index) + 1
    return text[open_index + 1 : close_index], line_offset


def split_table_entries(table: str, line_offset: int) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []
    depth = 0
    in_string = False
    in_char = False
    escape = False
    start: int | None = None
    for index, ch in enumerate(table):
        if in_string or in_char:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif in_string and ch == '"':
                in_string = False
            elif in_char and ch == "'":
                in_char = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "'":
            in_char = True
        elif ch == "{":
            if depth == 0:
                start = index
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                line_no = line_offset + table.count("\n", 0, start)
                entries.append((line_no, table[start : index + 1]))
                start = None
    return entries


def strip_outer_braces(value: str) -> str:
    stripped = value.strip()
    if not stripped.startswith("{") or not stripped.endswith("}"):
        raise ValueError(f"expected brace initializer: {value[:80]}")
    return stripped[1:-1]


def split_top_level_args(value: str) -> list[str]:
    fields: list[str] = []
    start = 0
    depth = 0
    in_string = False
    in_char = False
    escape = False
    for index, ch in enumerate(value):
        if in_string or in_char:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif in_string and ch == '"':
                in_string = False
            elif in_char and ch == "'":
                in_char = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "'":
            in_char = True
        elif ch in "({[":
            depth += 1
        elif ch in ")}]":
            depth -= 1
        elif ch == "," and depth == 0:
            fields.append(value[start:index].strip())
            start = index + 1
    tail = value[start:].strip()
    if tail:
        fields.append(tail)
    return fields


def parse_c_string_literals(value: str) -> str | None:
    if value.strip() == "NULL":
        return None
    strings = re.findall(r'"(?:\\.|[^"\\])*"', value)
    if not strings:
        return None
    parts: list[str] = []
    for item in strings:
        try:
            parsed = ast.literal_eval(item)
        except Exception:
            parsed = item[1:-1]
        parts.append(str(parsed))
    return "".join(parts)


def parse_c_char(value: str) -> str | None:
    value = value.strip()
    if value == "'\\0'":
        return None
    if re.fullmatch(r"'(?:\\.|[^'\\])'", value) is None:
        return None
    try:
        parsed = ast.literal_eval(value)
    except Exception:
        return value[1:-1]
    return str(parsed)


def normalize_argument_kind(value: str) -> str:
    value = value.strip()
    return {
        "no_argument": "none",
        "required_argument": "required",
        "optional_argument": "optional",
    }.get(value, value)


def dash_prefixes(dash_kind: str) -> list[str]:
    if dash_kind == "ONE_DASH":
        return ["-"]
    if dash_kind == "TWO_DASHES":
        return ["-", "--"]
    if dash_kind == "EXACTLY_TWO_DASHES":
        return ["--"]
    return []


def option_spellings(long_name: str | None, short_name: str | None, dash_kind: str) -> list[str]:
    spellings: list[str] = []
    if long_name:
        for prefix in dash_prefixes(dash_kind):
            spellings.append(prefix + long_name)
    if short_name:
        spelling = "-" + short_name
        if spelling not in spellings:
            spellings.append(spelling)
    return spellings


def parse_option_entry(line_no: int, entry: str, option_id: int) -> dict[str, object] | None:
    fields = split_top_level_args(strip_outer_braces(entry))
    if len(fields) < 5:
        return None
    getopt_fields = split_top_level_args(strip_outer_braces(fields[0]))
    if len(getopt_fields) < 4:
        return None
    long_name = parse_c_string_literals(getopt_fields[0])
    argument_kind = normalize_argument_kind(getopt_fields[1])
    code = getopt_fields[3].strip()
    short_name = parse_c_char(fields[1])
    meta_var = parse_c_string_literals(fields[2])
    help_text = parse_c_string_literals(fields[3])
    dash_kind = fields[4].strip()
    spellings = option_spellings(long_name, short_name, dash_kind)
    if not spellings:
        return None
    result: dict[str, object] = {
        "id": option_id,
        "spellings": spellings,
        "argument_kind": argument_kind,
        "code": code,
        "dash_kind": dash_kind,
        "source_location": f"{LEXSUP_PATH}:{line_no}",
    }
    if long_name is not None:
        result["long"] = long_name
    if short_name is not None:
        result["short"] = short_name
    if meta_var is not None:
        result["meta_var"] = meta_var
    if help_text is not None:
        result["help"] = help_text
    return result


def parse_ld_options(text: str) -> list[dict[str, object]]:
    table, line_offset = extract_ld_options_table(strip_c_comments(text))
    options: list[dict[str, object]] = []
    for line_no, entry in split_table_entries(table, line_offset):
        parsed = parse_option_entry(line_no, entry, len(options) + 1)
        if parsed is not None:
            options.append(parsed)
    return options


def generate_release(
    release: dict[str, str],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
) -> Path:
    version = release["version"]
    source_path = release.get("source_path", LEXSUP_PATH)
    data, source_sha = fetch_source(release["commit"], source_path, cache_dir)
    text = data.decode("utf-8", errors="replace")
    options = parse_ld_options(text)
    output = version_output_path(output_dir, version)
    lines = [
        "# Generated by scripts/update_ld_options.py --generate.",
        "# Do not edit by hand.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "schema_version": 1,
            "tool": "ld",
            "implementation": "gnu",
            "version": version,
            "source_repo": BINUTILS_REPO_URL,
            "source_tag": release["tag"],
            "source_commit": release["commit"],
            "source_path": source_path,
            "source_sha256": source_sha,
            "generator": "scripts/update_ld_options.py",
            "option_count": len(options),
        },
    )
    lines.append("")
    lines.append("[[source_files]]")
    write_table(
        lines,
        {"path": source_path, "ref": release["commit"], "sha256": source_sha},
    )
    lines.append("")
    for option in options:
        lines.append("[[options]]")
        write_table(lines, option)
        lines.append("")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output


def select_releases(
    releases: list[dict[str, str]],
    versions: list[str] | None,
) -> list[dict[str, str]]:
    if not versions:
        return releases
    wanted = set(versions)
    selected = [release for release in releases if release["version"] in wanted]
    found = {release["version"] for release in selected}
    missing = sorted(wanted - found, key=version_key)
    if missing:
        raise SystemExit(f"versions not in manifest: {', '.join(missing)}")
    return selected


def verify_outputs(
    releases: list[dict[str, str]],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
) -> None:
    with tempfile.TemporaryDirectory(prefix="ld-options-verify-") as tmp:
        temp_output = Path(tmp) / "option" / "ld"
        for release in releases:
            generate_release(
                release,
                metadata,
                output_dir=temp_output,
                cache_dir=cache_dir,
            )
        failures: list[str] = []
        for release in releases:
            rel = Path(major_version(release["version"])) / f"{release['version']}.toml"
            expected = output_dir / rel
            actual = temp_output / rel
            if not expected.exists():
                failures.append(f"missing generated file: {expected}")
                continue
            if expected.read_bytes() != actual.read_bytes():
                failures.append(f"not reproducible: {expected}")
    if failures:
        raise SystemExit("\n".join(failures))


def remove_stale_outputs(output_dir: Path, releases: list[dict[str, str]]) -> None:
    keep = {
        str(Path(major_version(release["version"])) / f"{release['version']}.toml")
        for release in releases
    }
    for path in output_dir.rglob("*.toml"):
        if path.name == "manifest.toml":
            continue
        rel = path.relative_to(output_dir).as_posix()
        if rel not in keep:
            path.unlink()
    for path in sorted(output_dir.iterdir(), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--refresh-manifest", action="store_true")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--versions", nargs="*", help="versions to process")
    args = parser.parse_args(argv)

    if args.refresh_manifest:
        refresh_manifest(args.manifest)

    if not args.generate and not args.verify and not args.clean:
        return 0

    metadata, releases = load_manifest(args.manifest)
    selected = select_releases(releases, args.versions)
    if args.generate:
        for release in selected:
            output = generate_release(
                release,
                metadata,
                output_dir=args.output_dir,
                cache_dir=args.cache_dir,
            )
            print(output.relative_to(ROOT))
    if args.clean:
        remove_stale_outputs(args.output_dir, releases)
    if args.verify:
        verify_outputs(
            selected,
            metadata,
            output_dir=args.output_dir,
            cache_dir=args.cache_dir,
        )
        print("ld option metadata is reproducible")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
