#!/usr/bin/env python3
"""Fetch and generate GCC option metadata from upstream .opt files."""

from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "option" / "gcc" / "manifest.toml"
DEFAULT_OUTPUT_DIR = ROOT / "option" / "gcc"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "gcc-options"
DEFAULT_FETCH_JOBS = int(os.environ.get("CXX_TOOLCHAINS_FETCH_JOBS", "16"))

GCC_REPO_URL = "https://github.com/gcc-mirror/gcc"
GCC_GIT_URL = "https://github.com/gcc-mirror/gcc.git"
GCC_RAW_URL = "https://raw.githubusercontent.com/gcc-mirror/gcc"

SKIPPED_RECORD_TYPES = {
    "Enum",
    "EnumValue",
    "HeaderInclude",
    "LangEnabledBy",
    "Language",
    "SourceInclude",
    "TargetSave",
    "TargetVariable",
    "Variable",
}


def run(
    args: list[str],
    *,
    cwd: Path | None = None,
    timeout: int = 300,
    capture: bool = True,
    text: bool = True,
) -> subprocess.CompletedProcess[str] | subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        args,
        cwd=cwd,
        check=True,
        timeout=timeout,
        text=text,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def semver_key(version: str) -> tuple[int, int, int, str]:
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)(.*)", version)
    if match is None:
        return (0, 0, 0, version)
    return (
        int(match.group(1)),
        int(match.group(2)),
        int(match.group(3)),
        match.group(4),
    )


def major_version(version: str) -> str:
    return version.split(".", 1)[0]


def version_output_path(output_dir: Path, version: str) -> Path:
    return output_dir / major_version(version) / f"{version}.toml"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch_bytes(url: str, timeout: int = 120, attempts: int = 5) -> bytes:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(url, timeout=timeout) as response:
                return response.read()
        except Exception as error:
            last_error = error
            if attempt + 1 == attempts:
                break
            time.sleep(0.5 * (attempt + 1))
    assert last_error is not None
    raise last_error


def fetch_source(ref: str, path: str, cache_dir: Path) -> tuple[bytes, str]:
    cache_path = cache_dir / "sources" / ref / path
    if cache_path.exists():
        data = cache_path.read_bytes()
        return data, sha256_bytes(data)

    data = fetch_bytes(f"{GCC_RAW_URL}/{ref}/{path}")
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_bytes(data)
    return data, sha256_bytes(data)


def raw_path_exists(ref: str, path: str) -> bool:
    try:
        with urlopen(f"{GCC_RAW_URL}/{ref}/{path}", timeout=30) as response:
            response.read(1)
        return True
    except Exception:
        return False


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: object) -> str:
    if value is None:
        raise ValueError("TOML does not support null values")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value: {type(value)!r}")


def write_table(lines: list[str], table: dict[str, object]) -> None:
    for key, value in table.items():
        if value is None:
            continue
        if isinstance(value, list) and len(value) == 0:
            lines.append(f"{key} = []")
            continue
        lines.append(f"{key} = {toml_value(value)}")


def write_manifest(path: Path, releases: list[dict[str, str]]) -> None:
    lines: list[str] = [
        "# Generated by scripts/update_gcc_options.py --refresh-manifest.",
        "# Edit only when intentionally changing the pinned source set.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "tool": "gcc",
            "source_repo": GCC_REPO_URL,
            "stable_only": True,
            "source_glob": "gcc/**/*.opt",
        },
    )
    lines.append("")

    for release in releases:
        lines.append("[[releases]]")
        write_table(lines, release)
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def refresh_manifest(path: Path) -> None:
    output = run(
        ["git", "ls-remote", "--tags", GCC_GIT_URL, "refs/tags/releases/gcc-*"],
        timeout=600,
    ).stdout

    tag_refs: dict[str, str] = {}
    peeled_tag_refs: dict[str, str] = {}
    for line in str(output).splitlines():
        sha, ref = line.split("\t", 1)
        if not ref.startswith("refs/tags/releases/gcc-"):
            continue
        peeled = ref.endswith("^{}")
        tag = ref.removesuffix("^{}").removeprefix("refs/tags/")
        version = tag.removeprefix("releases/gcc-")
        if re.fullmatch(r"\d+\.\d+\.\d+", version) is None:
            continue
        if peeled:
            peeled_tag_refs[version] = sha
        else:
            tag_refs[version] = sha

    releases = []
    tags = {**tag_refs, **peeled_tag_refs}
    for version, commit in sorted(tags.items(), key=lambda item: semver_key(item[0])):
        if not raw_path_exists(commit, "gcc/common.opt"):
            continue
        releases.append(
            {
                "version": version,
                "tag": f"releases/gcc-{version}",
                "commit": commit,
            }
        )
    write_manifest(path, releases)


def load_manifest(path: Path) -> tuple[dict[str, object], list[dict[str, str]]]:
    with path.open("rb") as file:
        data = tomllib.load(file)
    metadata = data.get("metadata", {})
    releases = data.get("releases", [])
    if not isinstance(metadata, dict) or not isinstance(releases, list):
        raise ValueError(f"invalid manifest shape: {path}")
    return metadata, releases


def ensure_git_cache(cache_dir: Path) -> Path:
    repo = cache_dir / "gcc.git"
    if repo.exists():
        run(["git", "--git-dir", str(repo), "remote", "set-url", "origin", GCC_GIT_URL])
        return repo
    repo.parent.mkdir(parents=True, exist_ok=True)
    run(["git", "init", "--bare", str(repo)], capture=False)
    run(["git", "--git-dir", str(repo), "remote", "add", "origin", GCC_GIT_URL])
    return repo


def ensure_release_available(repo: Path, release: dict[str, str]) -> None:
    commit = release["commit"]
    result = subprocess.run(
        ["git", "--git-dir", str(repo), "cat-file", "-e", f"{commit}^{{commit}}"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if result.returncode == 0:
        return
    tag = release["tag"]
    run(
        [
            "git",
            "--git-dir",
            str(repo),
            "fetch",
            "--filter=blob:none",
            "--depth=1",
            "origin",
            f"refs/tags/{tag}:refs/tags/{tag}",
        ],
        timeout=900,
        capture=False,
    )


def list_opt_paths(repo: Path, commit: str) -> list[str]:
    output = run(
        ["git", "--git-dir", str(repo), "ls-tree", "-r", "--name-only", commit, "--", "gcc"],
        timeout=300,
    ).stdout
    paths = []
    for line in str(output).splitlines():
        if not line.endswith(".opt"):
            continue
        if "/testsuite/" in line:
            continue
        paths.append(line)
    return sorted(paths)


def parse_blocks(text: str) -> list[tuple[int, list[str]]]:
    blocks: list[tuple[int, list[str]]] = []
    current: list[str] = []
    start_line = 0
    for line_no, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.strip()
        if not line:
            if current:
                blocks.append((start_line, current))
                current = []
            continue
        if line.startswith(";"):
            continue
        if not current:
            start_line = line_no
        current.append(line)
    if current:
        blocks.append((start_line, current))
    return blocks


def split_properties(value: str) -> list[str]:
    properties: list[str] = []
    start = 0
    depth = 0
    for index, ch in enumerate(value):
        if ch == "(":
            depth += 1
        elif ch == ")" and depth > 0:
            depth -= 1
        elif ch.isspace() and depth == 0:
            if start < index:
                properties.append(value[start:index])
            start = index + 1
    if start < len(value):
        properties.append(value[start:])
    return properties


def property_args(properties: list[str], name: str) -> list[str]:
    prefix = f"{name}("
    result = []
    for prop in properties:
        if prop.startswith(prefix) and prop.endswith(")"):
            result.append(prop[len(prefix) : -1])
    return result


def option_spelling(name: str) -> str:
    if name.startswith("-"):
        return name
    return f"-{name}"


def option_kind(name: str, flags: list[str]) -> str:
    if "JoinedOrMissing" in flags:
        return "joined-or-missing"
    if "Joined" in flags and "Separate" in flags:
        return "joined-or-separate"
    if "Joined" in flags or name.endswith("="):
        return "joined"
    if "Separate" in flags:
        return "separate"
    return "flag"


def collect_languages(blocks_by_file: list[tuple[str, list[tuple[int, list[str]]]]]) -> list[str]:
    languages: set[str] = set()
    for _, blocks in blocks_by_file:
        for _, block in blocks:
            if len(block) >= 2 and block[0] == "Language":
                languages.add(block[1])
    return sorted(languages)


def parse_release_files(
    repo: Path,
    release: dict[str, str],
    cache_dir: Path,
) -> tuple[list[dict[str, object]], list[dict[str, object]], list[dict[str, object]], list[dict[str, object]]]:
    commit = release["commit"]
    paths = list_opt_paths(repo, commit)
    blocks_by_file: list[tuple[str, list[tuple[int, list[str]]]]] = []
    source_files = []

    def fetch_path(path: str) -> tuple[str, bytes, str]:
        data, source_sha = fetch_source(commit, path, cache_dir)
        return path, data, source_sha

    with concurrent.futures.ThreadPoolExecutor(max_workers=DEFAULT_FETCH_JOBS) as executor:
        fetched = list(executor.map(fetch_path, paths))

    for path, data, source_sha in fetched:
        source_files.append({"path": path, "ref": commit, "sha256": source_sha})
        blocks_by_file.append((path, parse_blocks(data.decode("utf-8", errors="replace"))))

    languages = set(collect_languages(blocks_by_file))
    option_records: list[dict[str, object]] = []
    enums: list[dict[str, object]] = []
    enum_values: list[dict[str, object]] = []
    option_id = 0

    for path, blocks in blocks_by_file:
        for line_no, block in blocks:
            head = block[0]
            if head == "Enum":
                properties = split_properties(block[1]) if len(block) > 1 else []
                enum_name = property_args(properties, "Name")
                enum_type = property_args(properties, "Type")
                item: dict[str, object] = {
                    "name": enum_name[0] if enum_name else "",
                    "type": enum_type[0] if enum_type else "",
                    "properties": properties,
                    "source_location": f"{path}:{line_no}",
                }
                if len(block) > 2:
                    item["help"] = "\n".join(block[2:])
                enums.append(item)
                continue
            if head == "EnumValue":
                properties = split_properties(block[1]) if len(block) > 1 else []
                enum_name = property_args(properties, "Enum")
                string_value = property_args(properties, "String")
                value = property_args(properties, "Value")
                item = {
                    "enum": enum_name[0] if enum_name else "",
                    "string": string_value[0] if string_value else "",
                    "value": value[0] if value else "",
                    "properties": properties,
                    "source_location": f"{path}:{line_no}",
                }
                enum_values.append(item)
                continue
            if head in SKIPPED_RECORD_TYPES:
                continue
            if len(block) < 2:
                continue

            properties = split_properties(block[1])
            option_languages = [prop for prop in properties if prop in languages]
            function_properties = [prop for prop in properties if "(" in prop and prop.endswith(")")]
            flags = [
                prop
                for prop in properties
                if prop not in languages and prop not in function_properties
            ]
            option_id += 1
            aliases = property_args(properties, "Alias")
            variables = property_args(properties, "Var")
            enum_refs = property_args(properties, "Enum")
            missing_arg_errors = property_args(properties, "MissingArgError")
            enabled_by = property_args(properties, "EnabledBy")
            negative = property_args(properties, "Negative")
            item = {
                "id": option_id,
                "name": head,
                "spelling": option_spelling(head),
                "kind": option_kind(head, flags),
                "properties": properties,
                "flags": flags,
                "languages": option_languages,
                "source_location": f"{path}:{line_no}",
            }
            if aliases:
                item["alias"] = aliases[0]
            if variables:
                item["var"] = variables[0]
            if enum_refs:
                item["enum"] = enum_refs[0]
            if missing_arg_errors:
                item["missing_arg_error"] = missing_arg_errors[0]
            if enabled_by:
                item["enabled_by"] = enabled_by[0]
            if negative:
                item["negative"] = negative[0]
            if len(block) > 2:
                item["help"] = "\n".join(block[2:])
            option_records.append(item)

    return option_records, enums, enum_values, source_files


def generate_release(
    release: dict[str, str],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
) -> Path:
    version = release["version"]
    repo = ensure_git_cache(cache_dir)
    ensure_release_available(repo, release)
    option_records, enums, enum_values, source_files = parse_release_files(
        repo,
        release,
        cache_dir,
    )

    output = version_output_path(output_dir, version)
    lines: list[str] = [
        "# Generated by scripts/update_gcc_options.py --generate.",
        "# Do not edit by hand.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "schema_version": 1,
            "tool": "gcc",
            "version": version,
            "source_repo": GCC_REPO_URL,
            "source_tag": release["tag"],
            "source_commit": release["commit"],
            "source_glob": metadata.get("source_glob", "gcc/**/*.opt"),
            "generator": "scripts/update_gcc_options.py",
            "source_file_count": len(source_files),
            "option_count": len(option_records),
            "enum_count": len(enums),
            "enum_value_count": len(enum_values),
        },
    )
    lines.append("")

    for source_file in source_files:
        lines.append("[[source_files]]")
        write_table(lines, source_file)
        lines.append("")

    for enum in enums:
        lines.append("[[enums]]")
        write_table(lines, enum)
        lines.append("")

    for enum_value in enum_values:
        lines.append("[[enum_values]]")
        write_table(lines, enum_value)
        lines.append("")

    for record in option_records:
        lines.append("[[options]]")
        write_table(lines, record)
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output


def select_releases(
    releases: list[dict[str, str]],
    versions: list[str] | None,
) -> list[dict[str, str]]:
    if versions is None or len(versions) == 0:
        return releases
    wanted = set(versions)
    selected = [release for release in releases if release["version"] in wanted]
    found = {release["version"] for release in selected}
    missing = sorted(wanted - found, key=semver_key)
    if missing:
        raise SystemExit(f"versions not in manifest: {', '.join(missing)}")
    return selected


def verify_outputs(
    releases: list[dict[str, str]],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
) -> None:
    with tempfile.TemporaryDirectory(prefix="gcc-options-verify-") as tmp:
        temp_output = Path(tmp) / "option" / "gcc"
        for release in releases:
            generate_release(
                release,
                metadata,
                output_dir=temp_output,
                cache_dir=cache_dir,
            )

        failures: list[str] = []
        for release in releases:
            rel = Path(major_version(release["version"])) / f"{release['version']}.toml"
            expected = output_dir / rel
            actual = temp_output / rel
            if not expected.exists():
                failures.append(f"missing generated file: {expected}")
                continue
            if expected.read_bytes() != actual.read_bytes():
                failures.append(f"not reproducible: {expected}")

    if failures:
        raise SystemExit("\n".join(failures))


def remove_stale_outputs(output_dir: Path, releases: list[dict[str, str]]) -> None:
    keep = {
        str(Path(major_version(release["version"])) / f"{release['version']}.toml")
        for release in releases
    }
    for path in output_dir.rglob("*.toml"):
        if path.name == "manifest.toml":
            continue
        rel = path.relative_to(output_dir).as_posix()
        if rel not in keep:
            path.unlink()
    for path in sorted(output_dir.iterdir(), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--refresh-manifest", action="store_true")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--versions", nargs="*", help="versions to process")
    args = parser.parse_args(argv)

    if args.refresh_manifest:
        refresh_manifest(args.manifest)

    if not args.generate and not args.verify and not args.clean:
        return 0

    metadata, releases = load_manifest(args.manifest)
    selected = select_releases(releases, args.versions)

    if args.generate:
        for release in selected:
            output = generate_release(
                release,
                metadata,
                output_dir=args.output_dir,
                cache_dir=args.cache_dir,
            )
            print(output.relative_to(ROOT))

    if args.clean:
        remove_stale_outputs(args.output_dir, releases)

    if args.verify:
        verify_outputs(
            selected,
            metadata,
            output_dir=args.output_dir,
            cache_dir=args.cache_dir,
        )
        print("gcc option metadata is reproducible")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
