#!/usr/bin/env python3
"""Fetch and generate LLD option metadata from upstream TableGen files."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "option" / "lld" / "manifest.toml"
DEFAULT_OUTPUT_DIR = ROOT / "option" / "lld"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "llvm-options"

LLVM_REPO_URL = "https://github.com/llvm/llvm-project"
LLVM_GIT_URL = "https://github.com/llvm/llvm-project.git"
LLVM_RAW_URL = "https://raw.githubusercontent.com/llvm/llvm-project"

LLD_OPTION_PATHS = {
    "elf": "lld/ELF/Options.td",
    "coff": "lld/COFF/Options.td",
    "macho": "lld/MachO/Options.td",
    "mingw": "lld/MinGW/Options.td",
    "wasm": "lld/wasm/Options.td",
}
OPTPARSER_TD_PATH = "llvm/include/llvm/Option/OptParser.td"


def run(
    args: list[str],
    *,
    cwd: Path | None = None,
    timeout: int = 300,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=cwd,
        check=True,
        text=True,
        timeout=timeout,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def semver_key(version: str) -> tuple[int, int, int, str]:
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)(.*)", version)
    if match is None:
        return (0, 0, 0, version)
    return (
        int(match.group(1)),
        int(match.group(2)),
        int(match.group(3)),
        match.group(4),
    )


def major_version(version: str) -> str:
    return version.split(".", 1)[0]


def version_output_path(output_dir: Path, version: str) -> Path:
    return output_dir / major_version(version) / f"{version}.toml"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch_bytes(url: str, timeout: int = 120, attempts: int = 5) -> bytes:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(url, timeout=timeout) as response:
                return response.read()
        except Exception as error:
            last_error = error
            if attempt + 1 == attempts:
                break
            time.sleep(0.5 * (attempt + 1))
    assert last_error is not None
    raise last_error


def raw_path_exists(ref: str, path: str) -> bool:
    try:
        with urlopen(f"{LLVM_RAW_URL}/{ref}/{path}", timeout=5) as response:
            response.read(1)
        return True
    except Exception:
        return False


def fetch_source(ref: str, path: str, cache_dir: Path) -> tuple[Path, str]:
    cache_path = cache_dir / ref / path
    if cache_path.exists():
        data = cache_path.read_bytes()
        return cache_path, sha256_bytes(data)

    data = fetch_bytes(f"{LLVM_RAW_URL}/{ref}/{path}")
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_bytes(data)
    return cache_path, sha256_bytes(data)


def try_fetch_source(ref: str, path: str, cache_dir: Path) -> tuple[Path, str] | None:
    try:
        return fetch_source(ref, path, cache_dir)
    except Exception:
        return None


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: object) -> str:
    if value is None:
        raise ValueError("TOML does not support null values")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value: {type(value)!r}")


def write_table(lines: list[str], table: dict[str, object]) -> None:
    for key, value in table.items():
        if value is None:
            continue
        if isinstance(value, list) and len(value) == 0:
            lines.append(f"{key} = []")
            continue
        lines.append(f"{key} = {toml_value(value)}")


def write_manifest(path: Path, releases: list[dict[str, object]], include_rc: bool) -> None:
    lines = [
        "# Generated by scripts/update_lld_options.py --refresh-manifest.",
        "# Edit only when intentionally changing the pinned source set.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "tool": "lld",
            "source_repo": LLVM_REPO_URL,
            "stable_only": not include_rc,
            "driver_paths": [f"{driver}:{path}" for driver, path in LLD_OPTION_PATHS.items()],
            "optparser_path": OPTPARSER_TD_PATH,
        },
    )
    lines.append("")

    for release in releases:
        lines.append("[[releases]]")
        write_table(lines, release)
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def refresh_manifest(path: Path, include_rc: bool) -> None:
    output = run(
        ["git", "ls-remote", "--tags", LLVM_GIT_URL, "llvmorg-*"],
        timeout=600,
    ).stdout

    tag_refs: dict[str, str] = {}
    peeled_tag_refs: dict[str, str] = {}
    for line in output.splitlines():
        sha, ref = line.split("\t", 1)
        if not ref.startswith("refs/tags/"):
            continue
        peeled = ref.endswith("^{}")
        tag = ref.removesuffix("^{}").rsplit("/", 1)[1]
        version = tag.removeprefix("llvmorg-")
        if include_rc:
            ok = re.fullmatch(r"\d+\.\d+\.\d+(?:-rc\d+)?", version) is not None
        else:
            ok = re.fullmatch(r"\d+\.\d+\.\d+", version) is not None
        if not ok:
            continue
        if semver_key(version) < (9, 0, 0, ""):
            continue
        if peeled:
            peeled_tag_refs[version] = sha
        else:
            tag_refs[version] = sha

    releases = []
    tags = {**tag_refs, **peeled_tag_refs}
    for version, commit in sorted(tags.items(), key=lambda item: semver_key(item[0])):
        version_key = semver_key(version)
        drivers = []
        for driver, option_path in LLD_OPTION_PATHS.items():
            if driver == "macho" and version_key < (11, 0, 0, ""):
                continue
            drivers.append(f"{driver}:{option_path}")
        if not drivers:
            continue
        releases.append(
            {
                "version": version,
                "tag": f"llvmorg-{version}",
                "commit": commit,
                "drivers": drivers,
            }
        )
    write_manifest(path, releases, include_rc)


def load_manifest(path: Path) -> tuple[dict[str, object], list[dict[str, object]]]:
    with path.open("rb") as file:
        data = tomllib.load(file)
    metadata = data.get("metadata", {})
    releases = data.get("releases", [])
    if not isinstance(metadata, dict) or not isinstance(releases, list):
        raise ValueError(f"invalid manifest shape: {path}")
    return metadata, releases


def resolve_tblgen(path: str | None) -> str:
    if path is not None:
        resolved = shutil.which(path) if os.path.sep not in path else path
    else:
        resolved = shutil.which("llvm-tblgen")
    if resolved is None:
        raise SystemExit("llvm-tblgen not found; pass --tblgen or add it to PATH")
    return resolved


def parse_includes(text: str) -> list[str]:
    includes = []
    for line in text.splitlines():
        match = re.match(r'\s*include\s+"([^"]+)"', line)
        if match is not None:
            includes.append(match.group(1))
    return includes


def resolve_include_path(include: str, current_path: str, commit: str, cache_dir: Path) -> str | None:
    current_dir = str(Path(current_path).parent)
    if include == "llvm/Option/OptParser.td":
        return OPTPARSER_TD_PATH
    candidates = [
        str(Path(current_dir) / include),
        include,
        f"lld/include/{include}",
        f"llvm/include/{include}",
    ]
    seen: set[str] = set()
    for candidate in candidates:
        normalized = str(Path(candidate))
        if normalized in seen:
            continue
        seen.add(normalized)
        if try_fetch_source(commit, normalized, cache_dir) is not None:
            return normalized
    return None


def patch_optparser_for_current_tblgen(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    changed = False
    if "class SubCommand" not in text:
        marker = "class Option<"
        replacement = (
            'class SubCommand<string name, string helpText = "", string usage = ""> {\n'
            "  string Name = name;\n"
            "  string HelpText = helpText;\n"
            "  string Usage = usage;\n"
            "}\n\n"
            + marker
        )
        if marker in text:
            text = text.replace(marker, replacement, 1)
            changed = True
    if "SubCommands" not in text:
        lines = text.splitlines()
        in_option = False
        brace_depth = 0
        insert_at: int | None = None
        for index, line in enumerate(lines):
            if not in_option and line.startswith("class Option<"):
                in_option = True
            if in_option:
                brace_depth += line.count("{") - line.count("}")
                if "list<OptionVisibility> Visibility" in line:
                    insert_at = index + 1
                    break
                if brace_depth <= 0:
                    break
        if insert_at is not None:
            lines.insert(insert_at, "  list<SubCommand> SubCommands = [];")
            text = "\n".join(lines) + "\n"
            changed = True
    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def prepare_source_tree(
    release: dict[str, object],
    cache_dir: Path,
    work_dir: Path,
) -> dict[str, object]:
    commit = str(release["commit"])
    fetched: dict[str, str] = {}
    copied: set[tuple[str, str]] = set()
    queue = [driver_path.split(":", 1)[1] for driver_path in release["drivers"]]
    tablegen_compat_patches: list[str] = []

    while queue:
        path = queue.pop(0)
        key = (commit, path)
        if key in copied:
            continue

        src, source_sha = fetch_source(commit, path, cache_dir)
        dst = work_dir / path
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
        if path == OPTPARSER_TD_PATH and patch_optparser_for_current_tblgen(dst):
            tablegen_compat_patches.append(path)
        copied.add(key)
        fetched[f"{commit}:{path}"] = source_sha

        text = src.read_text(encoding="utf-8", errors="replace")
        for include in parse_includes(text):
            include_path = resolve_include_path(include, path, commit, cache_dir)
            if include_path is None:
                raise FileNotFoundError(
                    f"could not resolve include {include!r} from {path} at {commit}"
                )
            queue.append(include_path)

    return {
        "optparser_sha256": fetched.get(f"{commit}:{OPTPARSER_TD_PATH}", ""),
        "tablegen_compat_patches": tablegen_compat_patches,
        "source_files": [
            {"path": key.split(":", 1)[1], "ref": key.split(":", 1)[0], "sha256": value}
            for key, value in sorted(fetched.items())
        ],
    }


def ref_name(value: object) -> str | None:
    if isinstance(value, dict) and "def" in value:
        return str(value["def"])
    return None


def ref_names(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [name for item in value if (name := ref_name(item)) is not None]


def normalize_kind(kind: str | None) -> str | None:
    if kind is None:
        return None
    return kind.removeprefix("KIND_").lower().replace("_", "-")


def strip_c_comments(value: str) -> str:
    return re.sub(r"/\*.*?\*/", "", value, flags=re.S)


def split_top_level_args(value: str) -> list[str]:
    fields = []
    start = 0
    depth = 0
    in_string = False
    escape = False
    for index, ch in enumerate(value):
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch in "({[":
            depth += 1
        elif ch in ")}]":
            depth -= 1
        elif ch == "," and depth == 0:
            fields.append(value[start:index].strip())
            start = index + 1
    fields.append(value[start:].strip())
    return fields


def parse_option_order(generated: str) -> dict[str, int]:
    order: dict[str, int] = {}
    index = 0
    cursor = 0
    while True:
        start = generated.find("OPTION(", cursor)
        if start == -1:
            break
        pos = start + len("OPTION(")
        depth = 1
        in_string = False
        escape = False
        while pos < len(generated) and depth > 0:
            ch = generated[pos]
            if in_string:
                if escape:
                    escape = False
                elif ch == "\\":
                    escape = True
                elif ch == '"':
                    in_string = False
            else:
                if ch == '"':
                    in_string = True
                elif ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
            pos += 1

        body = generated[start + len("OPTION(") : pos - 1]
        fields = split_top_level_args(strip_c_comments(body))
        if len(fields) >= 3:
            index += 1
            order[strip_c_comments(fields[2]).strip()] = index
        cursor = pos
    return order


def option_record_to_toml(
    driver: str,
    record_name: str,
    record: dict[str, object],
    option_order: dict[str, int],
) -> dict[str, object]:
    enum = str(record.get("EnumName") or record_name)
    prefixes = [str(item) for item in record.get("Prefixes", [])]
    raw_name = str(record.get("Name", ""))
    spellings = [prefix + raw_name for prefix in prefixes] if prefixes else [raw_name]
    locs = record.get("!locs")
    result: dict[str, object] = {
        "driver": driver,
        "id": option_order.get(enum, 0),
        "record": record_name,
        "enum": enum,
        "kind": normalize_kind(ref_name(record.get("Kind"))),
        "name": raw_name,
        "prefixes": prefixes,
        "spellings": spellings,
        "flags": ref_names(record.get("Flags")),
        "visibility": ref_names(record.get("Visibility")),
        "num_args": int(record.get("NumArgs", 0) or 0),
    }
    group = ref_name(record.get("Group"))
    alias = ref_name(record.get("Alias"))
    if group is not None:
        result["group"] = group
    if alias is not None:
        result["alias"] = alias
    for source_key, target_key in [
        ("HelpText", "help"),
        ("MetaVarName", "meta_var"),
        ("Values", "values"),
        ("ValuesCode", "values_code"),
        ("KeyPath", "key_path"),
    ]:
        value = record.get(source_key)
        if isinstance(value, str):
            result[target_key] = value
    alias_args = record.get("AliasArgs")
    if isinstance(alias_args, list) and alias_args:
        result["alias_args"] = [str(item) for item in alias_args]
    if isinstance(locs, list) and locs:
        result["source_location"] = str(locs[0])
    return result


def source_order_key(record: dict[str, object]) -> tuple[str, int, str]:
    locs = record.get("!locs")
    if isinstance(locs, list) and locs:
        loc = str(locs[0])
        match = re.match(r"([^:]+):(\d+)", loc)
        if match is not None:
            return (match.group(1), int(match.group(2)), loc)
        return (loc, 0, loc)
    return ("", 0, "")


def generate_driver_options(
    release: dict[str, object],
    driver: str,
    path: str,
    *,
    work_dir: Path,
    tblgen: str,
) -> list[dict[str, object]]:
    include_args = [
        "-I",
        str(work_dir / "lld" / Path(path).parent.relative_to("lld")),
        "-I",
        str(work_dir / "lld" / "include"),
        "-I",
        str(work_dir / "llvm" / "include"),
        "-I",
        str(work_dir / "llvm" / "include" / "llvm" / "Option"),
    ]
    options_td = str(work_dir / path)
    dump = run([tblgen, "-dump-json", *include_args, options_td], timeout=600).stdout
    try:
        generated = run(
            [tblgen, "-gen-opt-parser-defs", *include_args, options_td],
            timeout=600,
        ).stdout
    except subprocess.CalledProcessError:
        generated = ""

    data = json.loads(dump)
    option_order = parse_option_order(generated)
    raw_records: list[tuple[str, dict[str, object]]] = []
    for record_name, record in data.items():
        if record_name.startswith("!") or not isinstance(record, dict):
            continue
        superclasses = record.get("!superclasses", [])
        if isinstance(superclasses, list) and "Option" in superclasses:
            raw_records.append((record_name, record))
    if not option_order:
        source_sorted = sorted(raw_records, key=lambda item: source_order_key(item[1]))
        option_order = {
            str(record.get("EnumName") or record_name): index
            for index, (record_name, record) in enumerate(source_sorted, start=1)
        }
    else:
        next_id = max(option_order.values(), default=0) + 1
        for record_name, record in sorted(raw_records, key=lambda item: source_order_key(item[1])):
            enum = str(record.get("EnumName") or record_name)
            if enum not in option_order:
                option_order[enum] = next_id
                next_id += 1
    records = [
        option_record_to_toml(driver, record_name, record, option_order)
        for record_name, record in raw_records
    ]
    records.sort(key=lambda item: (str(item["driver"]), int(item.get("id", 0)), str(item["enum"])))
    return records


def generate_release(
    release: dict[str, object],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
    tblgen: str,
) -> Path:
    version = str(release["version"])
    with tempfile.TemporaryDirectory(prefix=f"lld-options-{version}-") as tmp:
        work_dir = Path(tmp)
        source_meta = prepare_source_tree(release, cache_dir, work_dir)
        option_records: list[dict[str, object]] = []
        for driver_path in release["drivers"]:
            driver, path = str(driver_path).split(":", 1)
            option_records.extend(
                generate_driver_options(
                    release,
                    driver,
                    path,
                    work_dir=work_dir,
                    tblgen=tblgen,
                )
            )

    output = version_output_path(output_dir, version)
    lines = [
        "# Generated by scripts/update_lld_options.py --generate.",
        "# Do not edit by hand.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "schema_version": 1,
            "tool": "lld",
            "version": version,
            "source_repo": LLVM_REPO_URL,
            "source_tag": release["tag"],
            "source_commit": release["commit"],
            "drivers": release["drivers"],
            "optparser_path": OPTPARSER_TD_PATH,
            "optparser_sha256": source_meta["optparser_sha256"],
            "tablegen_compat_patches": source_meta["tablegen_compat_patches"],
            "generator": "scripts/update_lld_options.py",
            "option_count": len(option_records),
        },
    )
    lines.append("")

    for source_file in source_meta["source_files"]:
        lines.append("[[source_files]]")
        write_table(lines, source_file)
        lines.append("")

    for record in option_records:
        lines.append("[[options]]")
        write_table(lines, record)
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output


def select_releases(
    releases: list[dict[str, object]],
    versions: list[str] | None,
) -> list[dict[str, object]]:
    if versions is None or len(versions) == 0:
        return releases
    wanted = set(versions)
    selected = [release for release in releases if release["version"] in wanted]
    found = {str(release["version"]) for release in selected}
    missing = sorted(wanted - found, key=semver_key)
    if missing:
        raise SystemExit(f"versions not in manifest: {', '.join(missing)}")
    return selected


def verify_outputs(
    releases: list[dict[str, object]],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
    tblgen: str,
) -> None:
    with tempfile.TemporaryDirectory(prefix="lld-options-verify-") as tmp:
        temp_output = Path(tmp) / "option" / "lld"
        for release in releases:
            generate_release(
                release,
                metadata,
                output_dir=temp_output,
                cache_dir=cache_dir,
                tblgen=tblgen,
            )

        failures = []
        for release in releases:
            version = str(release["version"])
            rel = Path(major_version(version)) / f"{version}.toml"
            expected = output_dir / rel
            actual = temp_output / rel
            if not expected.exists():
                failures.append(f"missing generated file: {expected}")
                continue
            if expected.read_bytes() != actual.read_bytes():
                failures.append(f"not reproducible: {expected}")

    if failures:
        raise SystemExit("\n".join(failures))


def remove_stale_outputs(output_dir: Path, releases: list[dict[str, object]]) -> None:
    keep = {
        str(Path(major_version(str(release["version"]))) / f"{release['version']}.toml")
        for release in releases
    }
    for path in output_dir.rglob("*.toml"):
        if path.name == "manifest.toml":
            continue
        rel = path.relative_to(output_dir).as_posix()
        if rel not in keep:
            path.unlink()
    for path in sorted(output_dir.iterdir(), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--tblgen", help="path to llvm-tblgen")
    parser.add_argument("--refresh-manifest", action="store_true")
    parser.add_argument("--include-rc", action="store_true")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--versions", nargs="*", help="versions to process")
    args = parser.parse_args(argv)

    if args.refresh_manifest:
        refresh_manifest(args.manifest, include_rc=args.include_rc)

    if not args.generate and not args.verify and not args.clean:
        return 0

    metadata, releases = load_manifest(args.manifest)
    selected = select_releases(releases, args.versions)
    tblgen = resolve_tblgen(args.tblgen)

    if args.generate:
        for release in selected:
            output = generate_release(
                release,
                metadata,
                output_dir=args.output_dir,
                cache_dir=args.cache_dir,
                tblgen=tblgen,
            )
            print(output.relative_to(ROOT))

    if args.clean:
        remove_stale_outputs(args.output_dir, releases)

    if args.verify:
        verify_outputs(
            selected,
            metadata,
            output_dir=args.output_dir,
            cache_dir=args.cache_dir,
            tblgen=tblgen,
        )
        print("lld option metadata is reproducible")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
