#!/usr/bin/env python3
"""Fetch and generate Clang driver option metadata.

The generated TOML files are intentionally reproducible:

* option/clang/manifest.toml pins the LLVM release tags and commit SHAs.
* option/clang/<major>/<version>.toml is derived from pinned source paths.
* --verify regenerates into a temporary directory and byte-compares output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "option" / "clang" / "manifest.toml"
DEFAULT_OUTPUT_DIR = ROOT / "option" / "clang"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "llvm-options"

LLVM_REPO_URL = "https://github.com/llvm/llvm-project"
LLVM_GIT_URL = "https://github.com/llvm/llvm-project.git"
LLVM_RAW_URL = "https://raw.githubusercontent.com/llvm/llvm-project"

OPTIONS_TD_PATH = "clang/include/clang/Driver/Options.td"
OPTIONS_TD_PATHS = [
    "clang/include/clang/Driver/Options.td",
    "clang/include/clang/Options/Options.td",
]
OPTPARSER_TD_PATH = "llvm/include/llvm/Option/OptParser.td"
LEGACY_CLANG_OPTPARSER_TD_PATH = "clang/include/clang/Driver/OptParser.td"

def run(
    args: list[str],
    *,
    cwd: Path | None = None,
    timeout: int = 300,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=cwd,
        check=True,
        text=True,
        timeout=timeout,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def semver_key(version: str) -> tuple[int, int, int, str]:
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)(.*)", version)
    if match is None:
        return (0, 0, 0, version)
    return (
        int(match.group(1)),
        int(match.group(2)),
        int(match.group(3)),
        match.group(4),
    )


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch_bytes(url: str, timeout: int = 120, attempts: int = 5) -> bytes:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(url, timeout=timeout) as response:
                return response.read()
        except Exception as error:
            last_error = error
            if attempt + 1 == attempts:
                break
            time.sleep(0.5 * (attempt + 1))
    assert last_error is not None
    raise last_error


def raw_path_exists(ref: str, path: str) -> bool:
    try:
        with urlopen(f"{LLVM_RAW_URL}/{ref}/{path}", timeout=30) as response:
            response.read(1)
        return True
    except Exception:
        return False


def fetch_source(ref: str, path: str, cache_dir: Path) -> tuple[Path, str]:
    url = f"{LLVM_RAW_URL}/{ref}/{path}"
    cache_path = cache_dir / ref / path
    if cache_path.exists():
        data = cache_path.read_bytes()
        return cache_path, sha256_bytes(data)

    data = fetch_bytes(url)
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_bytes(data)
    return cache_path, sha256_bytes(data)


def try_fetch_source(ref: str, path: str, cache_dir: Path) -> tuple[Path, str] | None:
    try:
        return fetch_source(ref, path, cache_dir)
    except Exception:
        return None


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: object) -> str:
    if value is None:
        raise ValueError("TOML does not support null values")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value: {type(value)!r}")


def write_table(lines: list[str], table: dict[str, object]) -> None:
    for key, value in table.items():
        if value is None:
            continue
        if isinstance(value, list) and len(value) == 0:
            lines.append(f"{key} = []")
            continue
        lines.append(f"{key} = {toml_value(value)}")


def major_version(version: str) -> str:
    return version.split(".", 1)[0]


def version_output_path(output_dir: Path, version: str) -> Path:
    return output_dir / major_version(version) / f"{version}.toml"


def write_manifest(path: Path, releases: list[dict[str, str]], include_rc: bool) -> None:
    lines: list[str] = [
        "# Generated by scripts/update_clang_options.py --refresh-manifest.",
        "# Edit only when intentionally changing the pinned source set.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "tool": "clang",
            "source_repo": LLVM_REPO_URL,
            "stable_only": not include_rc,
            "options_paths": OPTIONS_TD_PATHS,
            "optparser_paths": [OPTPARSER_TD_PATH, LEGACY_CLANG_OPTPARSER_TD_PATH],
        },
    )
    lines.append("")

    for release in releases:
        lines.append("[[releases]]")
        write_table(lines, release)
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def refresh_manifest(path: Path, include_rc: bool) -> None:
    output = run(
        [
            "git",
            "ls-remote",
            "--tags",
            LLVM_GIT_URL,
            "llvmorg-*",
        ],
        timeout=600,
    ).stdout

    tag_refs: dict[str, str] = {}
    peeled_tag_refs: dict[str, str] = {}
    for line in output.splitlines():
        sha, ref = line.split("\t", 1)
        if not ref.startswith("refs/tags/"):
            continue
        peeled = ref.endswith("^{}")
        tag = ref.removesuffix("^{}").rsplit("/", 1)[1]
        version = tag.removeprefix("llvmorg-")
        if include_rc:
            ok = re.fullmatch(r"\d+\.\d+\.\d+(?:-rc\d+)?", version) is not None
        else:
            ok = re.fullmatch(r"\d+\.\d+\.\d+", version) is not None
        if ok and semver_key(version) < (3, 0, 0, ""):
            ok = False
        if not ok:
            continue
        if peeled:
            peeled_tag_refs[version] = sha
        else:
            tag_refs[version] = sha

    releases = []
    tags = {**tag_refs, **peeled_tag_refs}
    for version, commit in sorted(tags.items(), key=lambda item: semver_key(item[0])):
        options_path = next(
            (path for path in OPTIONS_TD_PATHS if raw_path_exists(commit, path)),
            None,
        )
        if options_path is None:
            continue
        releases.append(
            {
                "version": version,
                "tag": f"llvmorg-{version}",
                "commit": commit,
                "options_path": options_path,
            }
        )
    write_manifest(path, releases, include_rc)


def load_manifest(path: Path) -> tuple[dict[str, object], list[dict[str, str]]]:
    with path.open("rb") as file:
        data = tomllib.load(file)
    metadata = data.get("metadata", {})
    releases = data.get("releases", [])
    if not isinstance(metadata, dict) or not isinstance(releases, list):
        raise ValueError(f"invalid manifest shape: {path}")
    return metadata, releases


def resolve_tblgen(path: str | None) -> str:
    if path is not None:
        resolved = shutil.which(path) if os.path.sep not in path else path
    else:
        resolved = shutil.which("llvm-tblgen")
    if resolved is None:
        raise SystemExit("llvm-tblgen not found; pass --tblgen or add it to PATH")
    return resolved


def parse_includes(text: str) -> list[str]:
    includes: list[str] = []
    for line in text.splitlines():
        match = re.match(r'\s*include\s+"([^"]+)"', line)
        if match is not None:
            includes.append(match.group(1))
    return includes


def resolve_include_path(
    include: str,
    current_path: str,
    commit: str,
    cache_dir: Path,
) -> str | None:
    current_dir = str(Path(current_path).parent)
    candidates: list[str]
    if include == "llvm/Option/OptParser.td":
        return OPTPARSER_TD_PATH
    if include == "OptParser.td":
        candidates = [
            str(Path(current_dir) / include),
            LEGACY_CLANG_OPTPARSER_TD_PATH,
        ]
    elif "/" in include:
        candidates = [
            include,
            f"clang/include/{include}",
            f"llvm/include/{include}",
        ]
    else:
        candidates = [
            str(Path(current_dir) / include),
            str(Path(current_dir) / include),
            f"clang/include/clang/Driver/{include}",
            f"clang/include/clang/Options/{include}",
            f"clang/include/{include}",
            f"llvm/include/{include}",
        ]

    seen: set[str] = set()
    for candidate in candidates:
        normalized = str(Path(candidate))
        if normalized in seen:
            continue
        seen.add(normalized)
        if try_fetch_source(commit, normalized, cache_dir) is not None:
            return normalized
    return None


def prepare_source_tree(
    release: dict[str, str],
    metadata: dict[str, object],
    cache_dir: Path,
    work_dir: Path,
) -> dict[str, object]:
    commit = release["commit"]
    fetched: dict[str, str] = {}
    copied: set[tuple[str, str]] = set()
    options_path = release.get("options_path", OPTIONS_TD_PATH)
    queue = [options_path]
    legacy_optparser = False
    tablegen_compat_patches: list[str] = []

    while queue:
        path = queue.pop(0)
        ref = commit
        key = (ref, path)
        if key in copied:
            continue

        src, source_sha = fetch_source(ref, path, cache_dir)
        dst = work_dir / path
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
        if path in {OPTPARSER_TD_PATH, LEGACY_CLANG_OPTPARSER_TD_PATH}:
            if patch_optparser_for_current_tblgen(dst):
                tablegen_compat_patches.append(path)
        copied.add(key)
        fetched[f"{ref}:{path}"] = source_sha

        text = src.read_text(encoding="utf-8", errors="replace")
        for include in parse_includes(text):
            if include == "llvm/Option/OptParser.td":
                include_path = OPTPARSER_TD_PATH
            else:
                include_path = resolve_include_path(include, path, commit, cache_dir)
            if include_path is None:
                raise FileNotFoundError(
                    f"could not resolve include {include!r} from {path} at {commit}"
                )
            if include_path == LEGACY_CLANG_OPTPARSER_TD_PATH:
                legacy_optparser = True
            queue.append(include_path)

    optparser_key = (
        f"{commit}:{LEGACY_CLANG_OPTPARSER_TD_PATH}"
        if legacy_optparser
        else f"{commit}:{OPTPARSER_TD_PATH}"
    )
    return {
        "options_sha256": fetched[f"{commit}:{options_path}"],
        "options_path": options_path,
        "optparser_sha256": fetched.get(optparser_key, ""),
        "optparser_ref": commit,
        "optparser_path": LEGACY_CLANG_OPTPARSER_TD_PATH if legacy_optparser else OPTPARSER_TD_PATH,
        "legacy_optparser": legacy_optparser,
        "tablegen_compat_patches": tablegen_compat_patches,
        "source_files": [
            {"path": key.split(":", 1)[1], "ref": key.split(":", 1)[0], "sha256": value}
            for key, value in sorted(fetched.items())
        ],
    }


def patch_optparser_for_current_tblgen(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    changed = False
    if "class SubCommand" not in text:
        marker = "class Option<"
        replacement = (
            'class SubCommand<string name, string helpText = "", string usage = ""> {\n'
            "  string Name = name;\n"
            "  string HelpText = helpText;\n"
            "  string Usage = usage;\n"
            "}\n\n"
            + marker
        )
        if marker in text:
            text = text.replace(marker, replacement, 1)
            changed = True
    if "SubCommands" not in text:
        lines = text.splitlines()
        in_option = False
        brace_depth = 0
        insert_at: int | None = None
        for index, line in enumerate(lines):
            if not in_option and line.startswith("class Option<"):
                in_option = True
            if in_option:
                brace_depth += line.count("{") - line.count("}")
                if "list<OptionVisibility> Visibility" in line:
                    insert_at = index + 1
                    break
                if brace_depth <= 0:
                    break
        if insert_at is not None:
            lines.insert(insert_at, "  list<SubCommand> SubCommands = [];")
            text = "\n".join(lines) + "\n"
            changed = True
    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def ref_name(value: object) -> str | None:
    if isinstance(value, dict) and "def" in value:
        return str(value["def"])
    return None


def ref_names(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [name for item in value if (name := ref_name(item)) is not None]


def normalize_kind(kind: str | None) -> str | None:
    if kind is None:
        return None
    return kind.removeprefix("KIND_").lower().replace("_", "-")


def parse_option_order(generated: str) -> dict[str, int]:
    order: dict[str, int] = {}
    index = 0
    cursor = 0
    while True:
        start = generated.find("OPTION(", cursor)
        if start == -1:
            break
        pos = start + len("OPTION(")
        depth = 1
        in_string = False
        escape = False
        while pos < len(generated) and depth > 0:
            ch = generated[pos]
            if in_string:
                if escape:
                    escape = False
                elif ch == "\\":
                    escape = True
                elif ch == '"':
                    in_string = False
            else:
                if ch == '"':
                    in_string = True
                elif ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
            pos += 1

        body = generated[start + len("OPTION(") : pos - 1]
        fields = split_top_level_args(strip_c_comments(body))
        if len(fields) >= 3:
            index += 1
            order[strip_c_comments(fields[2]).strip()] = index
        cursor = pos
    return order


def split_top_level_args(value: str) -> list[str]:
    fields: list[str] = []
    start = 0
    depth = 0
    in_string = False
    escape = False
    for index, ch in enumerate(value):
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch in "({[":
            depth += 1
        elif ch in ")}]":
            depth -= 1
        elif ch == "," and depth == 0:
            fields.append(value[start:index].strip())
            start = index + 1
    fields.append(value[start:].strip())
    return fields


def strip_c_comments(value: str) -> str:
    return re.sub(r"/\*.*?\*/", "", value, flags=re.S)


def option_record_to_toml(
    record_name: str,
    record: dict[str, object],
    option_order: dict[str, int],
) -> dict[str, object]:
    enum = record.get("EnumName") or record_name
    enum = str(enum)
    prefixes = [str(item) for item in record.get("Prefixes", [])]
    raw_name = str(record.get("Name", ""))
    spellings = [prefix + raw_name for prefix in prefixes] if prefixes else [raw_name]
    group = ref_name(record.get("Group"))
    alias = ref_name(record.get("Alias"))
    help_text = record.get("HelpText")
    meta_var = record.get("MetaVarName")
    values = record.get("Values")
    values_code = record.get("ValuesCode")
    key_path = record.get("KeyPath")
    locs = record.get("!locs")

    result: dict[str, object] = {
        "id": option_order.get(enum, 0),
        "record": record_name,
        "enum": enum,
        "kind": normalize_kind(ref_name(record.get("Kind"))),
        "name": raw_name,
        "prefixes": prefixes,
        "spellings": spellings,
        "flags": ref_names(record.get("Flags")),
        "visibility": ref_names(record.get("Visibility")),
        "num_args": int(record.get("NumArgs", 0) or 0),
    }
    if group is not None:
        result["group"] = group
    if alias is not None:
        result["alias"] = alias
    alias_args = record.get("AliasArgs")
    if isinstance(alias_args, list) and len(alias_args) > 0:
        result["alias_args"] = [str(item) for item in alias_args]
    if isinstance(help_text, str):
        result["help"] = help_text
    if isinstance(meta_var, str):
        result["meta_var"] = meta_var
    if isinstance(values, str):
        result["values"] = values
    if isinstance(values_code, str):
        result["values_code"] = values_code
    if isinstance(key_path, str):
        result["key_path"] = key_path
    if isinstance(locs, list) and len(locs) > 0:
        result["source_location"] = str(locs[0])
    return result


def source_order_key(record: dict[str, object]) -> tuple[str, int, str]:
    locs = record.get("!locs")
    if isinstance(locs, list) and locs:
        loc = str(locs[0])
        match = re.match(r"([^:]+):(\d+)", loc)
        if match is not None:
            return (match.group(1), int(match.group(2)), loc)
        return (loc, 0, loc)
    return ("", 0, "")


def generate_release(
    release: dict[str, str],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
    tblgen: str,
) -> Path:
    version = release["version"]
    with tempfile.TemporaryDirectory(prefix=f"clang-options-{version}-") as tmp:
        work_dir = Path(tmp)
        source_meta = prepare_source_tree(release, metadata, cache_dir, work_dir)

        include_args = [
            "-I",
            str(work_dir / "clang" / "include"),
            "-I",
            str(work_dir / "clang" / "include" / "clang" / "Driver"),
            "-I",
            str(work_dir / "llvm" / "include"),
            "-I",
            str(work_dir / "llvm" / "include" / "llvm" / "Option"),
        ]
        options_td = str(work_dir / str(source_meta["options_path"]))
        dump = run([tblgen, "-dump-json", *include_args, options_td], timeout=600).stdout
        try:
            generated = run(
                [tblgen, "-gen-opt-parser-defs", *include_args, options_td],
                timeout=600,
            ).stdout
        except subprocess.CalledProcessError:
            generated = ""

    data = json.loads(dump)
    option_order = parse_option_order(generated)
    raw_option_records: list[tuple[str, dict[str, object]]] = []
    for record_name, record in data.items():
        if record_name.startswith("!") or not isinstance(record, dict):
            continue
        superclasses = record.get("!superclasses", [])
        if isinstance(superclasses, list) and "Option" in superclasses:
            raw_option_records.append((record_name, record))

    option_records = [
        option_record_to_toml(record_name, record, option_order)
        for record_name, record in raw_option_records
    ]
    if not option_order:
        source_sorted = sorted(raw_option_records, key=lambda item: source_order_key(item[1]))
        fallback_order = {
            str(record.get("EnumName") or record_name): index
            for index, (record_name, record) in enumerate(source_sorted, start=1)
        }
        option_records = [
            option_record_to_toml(record_name, record, fallback_order)
            for record_name, record in raw_option_records
        ]

    option_records.sort(key=lambda item: (int(item.get("id", 0)), str(item["enum"])))

    output = version_output_path(output_dir, version)
    lines: list[str] = [
        "# Generated by scripts/update_clang_options.py --generate.",
        "# Do not edit by hand.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "schema_version": 1,
            "tool": "clang",
            "version": version,
            "source_repo": LLVM_REPO_URL,
            "source_tag": release["tag"],
            "source_commit": release["commit"],
            "source_path": str(source_meta["options_path"]),
            "source_sha256": source_meta["options_sha256"],
            "optparser_path": str(source_meta["optparser_path"]),
            "optparser_ref": source_meta["optparser_ref"],
            "optparser_sha256": source_meta["optparser_sha256"],
            "legacy_optparser": bool(source_meta["legacy_optparser"]),
            "tablegen_compat_patches": source_meta["tablegen_compat_patches"],
            "generator": "scripts/update_clang_options.py",
            "option_count": len(option_records),
        },
    )
    lines.append("")

    source_files = source_meta["source_files"]
    if isinstance(source_files, list):
        for source_file in source_files:
            if not isinstance(source_file, dict):
                continue
            lines.append("[[source_files]]")
            write_table(lines, source_file)
            lines.append("")

    for record in option_records:
        lines.append("[[options]]")
        write_table(lines, record)
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output


def select_releases(
    releases: list[dict[str, str]],
    versions: list[str] | None,
) -> list[dict[str, str]]:
    if versions is None or len(versions) == 0:
        return releases
    wanted = set(versions)
    selected = [release for release in releases if release["version"] in wanted]
    found = {release["version"] for release in selected}
    missing = sorted(wanted - found, key=semver_key)
    if missing:
        raise SystemExit(f"versions not in manifest: {', '.join(missing)}")
    return selected


def verify_outputs(
    releases: list[dict[str, str]],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
    tblgen: str,
) -> None:
    with tempfile.TemporaryDirectory(prefix="clang-options-verify-") as tmp:
        temp_output = Path(tmp) / "option" / "clang"
        for release in releases:
            generate_release(
                release,
                metadata,
                output_dir=temp_output,
                cache_dir=cache_dir,
                tblgen=tblgen,
            )

        failures: list[str] = []
        for release in releases:
            rel = Path(major_version(release["version"])) / f"{release['version']}.toml"
            expected = output_dir / rel
            actual = temp_output / rel
            if not expected.exists():
                failures.append(f"missing generated file: {expected}")
                continue
            if expected.read_bytes() != actual.read_bytes():
                failures.append(f"not reproducible: {expected}")

    if failures:
        raise SystemExit("\n".join(failures))


def remove_stale_outputs(output_dir: Path, releases: list[dict[str, str]]) -> None:
    keep = {
        str(Path(major_version(release["version"])) / f"{release['version']}.toml")
        for release in releases
    }
    for path in output_dir.rglob("*.toml"):
        if path.name == "manifest.toml":
            continue
        rel = path.relative_to(output_dir).as_posix()
        if rel not in keep:
            path.unlink()
    for path in sorted(output_dir.iterdir(), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--tblgen", help="path to llvm-tblgen")
    parser.add_argument("--refresh-manifest", action="store_true")
    parser.add_argument("--include-rc", action="store_true")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--versions", nargs="*", help="versions to process")
    args = parser.parse_args(argv)

    if args.refresh_manifest:
        refresh_manifest(args.manifest, include_rc=args.include_rc)

    if not args.generate and not args.verify and not args.clean:
        return 0

    metadata, releases = load_manifest(args.manifest)
    selected = select_releases(releases, args.versions)
    tblgen = resolve_tblgen(args.tblgen)

    if args.generate:
        for release in selected:
            output = generate_release(
                release,
                metadata,
                output_dir=args.output_dir,
                cache_dir=args.cache_dir,
                tblgen=tblgen,
            )
            print(output.relative_to(ROOT))

    if args.clean:
        remove_stale_outputs(args.output_dir, releases)

    if args.verify:
        verify_outputs(
            selected,
            metadata,
            output_dir=args.output_dir,
            cache_dir=args.cache_dir,
            tblgen=tblgen,
        )
        print("clang option metadata is reproducible")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
