#!/usr/bin/env python3
"""Fetch and generate NVCC option metadata from versioned CUDA documentation."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
import tempfile
import time
import tomllib
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "option" / "nvcc" / "manifest.toml"
DEFAULT_OUTPUT_DIR = ROOT / "option" / "nvcc"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "nvcc-options"

CUDA_ARCHIVE_URL = "https://docs.nvidia.com/cuda/archive/"
NVCC_DOC_PATH = "cuda-compiler-driver-nvcc/index.html"
SHA256_RE = re.compile(r"[0-9a-f]{64}")
ALIAS_RE = re.compile(r"-[A-Za-z0-9][A-Za-z0-9_-]*")


def version_key(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


def normalize_version(version: str) -> str:
    parts = version.split(".")
    while len(parts) < 3:
        parts.append("0")
    return ".".join(parts)


def major_version(version: str) -> str:
    return version.split(".", 1)[0]


def version_output_path(output_dir: Path, version: str) -> Path:
    return output_dir / major_version(version) / f"{version}.toml"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch_bytes(url: str, timeout: int = 120, attempts: int = 5) -> bytes:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(url, timeout=timeout) as response:
                return response.read()
        except Exception as error:
            last_error = error
            if attempt + 1 == attempts:
                break
            time.sleep(0.5 * (attempt + 1))
    assert last_error is not None
    raise last_error


def doc_url(version_path: str) -> str:
    return f"{CUDA_ARCHIVE_URL}{version_path}/{NVCC_DOC_PATH}"


def validate_source_sha256(version: str, source_sha256: object) -> str:
    if not isinstance(source_sha256, str) or SHA256_RE.fullmatch(source_sha256) is None:
        raise ValueError(f"release {version} is missing a valid source_sha256")
    return source_sha256


def fetch_source(version: str, source_url: str, cache_dir: Path, expected_sha256: str) -> tuple[bytes, str]:
    cache_path = cache_dir / "sources" / version / "index.html"
    if cache_path.exists():
        data = cache_path.read_bytes()
        source_sha = sha256_bytes(data)
        if source_sha == expected_sha256:
            return data, source_sha
    data = fetch_bytes(source_url)
    source_sha = sha256_bytes(data)
    if source_sha != expected_sha256:
        raise ValueError(
            f"source hash mismatch for {version}: expected {expected_sha256}, got {source_sha} from {source_url}"
        )
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_bytes(data)
    return data, source_sha


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_value(value: object) -> str:
    if value is None:
        raise ValueError("TOML does not support null values")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value: {type(value)!r}")


def write_table(lines: list[str], table: dict[str, object]) -> None:
    for key, value in table.items():
        if value is None:
            continue
        if isinstance(value, list) and len(value) == 0:
            lines.append(f"{key} = []")
            continue
        lines.append(f"{key} = {toml_value(value)}")


def clean_html(value: str) -> str:
    value = re.sub(r'<span class="pre">(.*?)</span>', lambda match: match.group(1), value, flags=re.S)
    value = re.sub(r"<[^>]+>", " ", value)
    value = html.unescape(value)
    value = value.replace("\uf0c1", "")
    return re.sub(r"\s+", " ", value).strip()


def write_manifest(path: Path, releases: list[dict[str, str]]) -> None:
    lines = [
        "# Generated by scripts/update_nvcc_options.py --refresh-manifest.",
        "# Edit only when intentionally changing the pinned source set.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "tool": "nvcc",
            "source_repo": "https://docs.nvidia.com/cuda/archive/",
            "stable_only": True,
            "source_path": NVCC_DOC_PATH,
        },
    )
    lines.append("")
    for release in releases:
        lines.append("[[releases]]")
        write_table(lines, release)
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def refresh_manifest(path: Path) -> None:
    data = fetch_bytes(CUDA_ARCHIVE_URL).decode("utf-8", errors="replace")
    version_paths = {
        normalize_version(match): match
        for match in re.findall(r'href="([0-9]+\.[0-9]+(?:\.[0-9]+)?)/index\.html"', data)
    }
    versions = sorted(version_paths, key=version_key)
    releases = []
    for version in versions:
        source_url = doc_url(version_paths[version])
        source_data = fetch_bytes(source_url)
        releases.append(
            {
                "version": version,
                "source_url": source_url,
                "source_path": NVCC_DOC_PATH,
                "source_sha256": sha256_bytes(source_data),
            }
        )
    write_manifest(path, releases)


def load_manifest(path: Path) -> tuple[dict[str, object], list[dict[str, str]]]:
    with path.open("rb") as file:
        data = tomllib.load(file)
    metadata = data.get("metadata", {})
    releases = data.get("releases", [])
    if not isinstance(metadata, dict) or not isinstance(releases, list):
        raise ValueError(f"invalid manifest shape: {path}")
    for release in releases:
        if not isinstance(release, dict):
            raise ValueError(f"invalid release entry in manifest: {path}")
        version = release.get("version")
        source_url = release.get("source_url")
        if not isinstance(version, str) or not isinstance(source_url, str):
            raise ValueError(f"invalid release entry in manifest: {path}")
        validate_source_sha256(version, release.get("source_sha256"))
    return metadata, releases


def is_alias_spelling(value: str) -> bool:
    return ALIAS_RE.fullmatch(value) is not None


def parse_synopsis(text: str) -> dict[str, object] | None:
    match = re.match(r"(?P<section>\d+(?:\.\d+)+)\.?\s+(?P<synopsis>--.+)$", text)
    if match is None:
        return None
    synopsis = match.group("synopsis").strip()
    long_match = re.search(r"--[A-Za-z0-9][A-Za-z0-9_-]*", synopsis)
    if long_match is None:
        return None
    long_name = long_match.group(0)
    alias_match = re.search(r"\(\s*(?P<aliases>-[^)]+?)\s*\)\s*$", synopsis)
    aliases = []
    if alias_match is not None:
        aliases = [
            re.sub(r"\s+", " ", item).strip()
            for item in alias_match.group("aliases").split("|")
            if is_alias_spelling(re.sub(r"\s+", " ", item).strip())
        ]
    argument_text = synopsis[long_match.end() : alias_match.start() if alias_match else len(synopsis)].strip()
    return {
        "section": match.group("section"),
        "synopsis": synopsis,
        "long": long_name,
        "aliases": aliases,
        "argument_text": argument_text,
        "argument_kind": "none" if argument_text == "" else "required",
    }


def first_paragraph_after_anchor(document: str, anchor: str) -> str | None:
    anchor_index = document.find(f'id="{anchor}"')
    if anchor_index == -1:
        anchor_index = document.find(f'name="{anchor}"')
    if anchor_index == -1:
        return None
    chunk = document[anchor_index : anchor_index + 8000]
    paragraph = re.search(r"<p[^>]*>(.*?)</p>", chunk, re.S)
    if paragraph is None:
        return None
    text = clean_html(paragraph.group(1))
    return text or None


def parse_toc_options(document: str) -> list[dict[str, object]]:
    options: list[dict[str, object]] = []
    seen: set[str] = set()
    for match in re.finditer(r'<a\s+[^>]*href="#([^"]+)"[^>]*>(.*?)</a>', document, re.S):
        anchor = match.group(1)
        text = clean_html(match.group(2))
        if "--" not in text or re.match(r"\d+(?:\.\d+)+\.?", text) is None:
            continue
        parsed = parse_synopsis(text)
        if parsed is None:
            continue
        key = str(parsed["long"])
        if key in seen:
            continue
        seen.add(key)
        parsed["anchor"] = anchor
        help_text = first_paragraph_after_anchor(document, anchor)
        if help_text is not None:
            parsed["help"] = help_text
        options.append(parsed)
    return options


def parse_table_options(document: str) -> list[dict[str, object]]:
    options: list[dict[str, object]] = []
    seen: set[str] = set()
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", document, re.S):
        cells = re.findall(r"<(?:td|entry)[^>]*>(.*?)</(?:td|entry)>", row, re.S)
        if len(cells) < 3:
            continue
        cleaned = [clean_html(cell) for cell in cells]
        long_cell = next((cell for cell in cleaned if "--" in cell), "")
        if not long_cell:
            continue
        long_match = re.search(r"--[A-Za-z0-9][A-Za-z0-9_-]*", long_cell)
        if long_match is None:
            continue
        long_name = long_match.group(0)
        if long_name in seen:
            continue
        seen.add(long_name)
        alias = next((cell for cell in cleaned if re.fullmatch(r"-[A-Za-z0-9][A-Za-z0-9_-]*", cell)), "")
        help_text = cleaned[-1]
        argument_text = long_cell[long_match.end() :].strip()
        options.append(
            {
                "synopsis": long_cell + (f" ({alias})" if alias else ""),
                "long": long_name,
                "aliases": [alias] if alias else [],
                "argument_text": argument_text,
                "argument_kind": "none" if argument_text == "" else "required",
                "help": help_text,
            }
        )
    return options


def parse_nvcc_options(document: str) -> list[dict[str, object]]:
    parsed = parse_toc_options(document)
    if not parsed:
        parsed = parse_table_options(document)
    options = []
    for index, option in enumerate(parsed, start=1):
        spellings = [str(option["long"]), *[str(alias) for alias in option["aliases"]]]
        result = {
            "id": index,
            "spellings": spellings,
            "long": str(option["long"]),
            "aliases": [str(alias) for alias in option["aliases"]],
            "argument_kind": str(option["argument_kind"]),
            "synopsis": str(option["synopsis"]),
        }
        for key in ["section", "anchor", "argument_text", "help"]:
            value = option.get(key)
            if isinstance(value, str) and value:
                result[key] = value
        options.append(result)
    return options


def generate_release(
    release: dict[str, str],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
) -> Path:
    version = release["version"]
    source_url = release["source_url"]
    expected_source_sha = validate_source_sha256(version, release.get("source_sha256"))
    data, source_sha = fetch_source(version, source_url, cache_dir, expected_source_sha)
    document = data.decode("utf-8", errors="replace")
    options = parse_nvcc_options(document)
    output = version_output_path(output_dir, version)
    lines = [
        "# Generated by scripts/update_nvcc_options.py --generate.",
        "# Do not edit by hand.",
        "",
        "[metadata]",
    ]
    write_table(
        lines,
        {
            "schema_version": 1,
            "tool": "nvcc",
            "version": version,
            "source_url": source_url,
            "source_path": release.get("source_path", NVCC_DOC_PATH),
            "source_sha256": source_sha,
            "generator": "scripts/update_nvcc_options.py",
            "option_count": len(options),
        },
    )
    lines.append("")
    lines.append("[[source_files]]")
    write_table(
        lines,
        {"path": release.get("source_path", NVCC_DOC_PATH), "url": source_url, "sha256": source_sha},
    )
    lines.append("")
    for option in options:
        lines.append("[[options]]")
        write_table(lines, option)
        lines.append("")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output


def select_releases(
    releases: list[dict[str, str]],
    versions: list[str] | None,
) -> list[dict[str, str]]:
    if not versions:
        return releases
    wanted = set(versions)
    selected = [release for release in releases if release["version"] in wanted]
    found = {release["version"] for release in selected}
    missing = sorted(wanted - found, key=version_key)
    if missing:
        raise SystemExit(f"versions not in manifest: {', '.join(missing)}")
    return selected


def verify_outputs(
    releases: list[dict[str, str]],
    metadata: dict[str, object],
    *,
    output_dir: Path,
    cache_dir: Path,
) -> None:
    with tempfile.TemporaryDirectory(prefix="nvcc-options-verify-") as tmp:
        temp_output = Path(tmp) / "option" / "nvcc"
        for release in releases:
            generate_release(release, metadata, output_dir=temp_output, cache_dir=cache_dir)
        failures: list[str] = []
        for release in releases:
            rel = Path(major_version(release["version"])) / f"{release['version']}.toml"
            expected = output_dir / rel
            actual = temp_output / rel
            if not expected.exists():
                failures.append(f"missing generated file: {expected}")
                continue
            if expected.read_bytes() != actual.read_bytes():
                failures.append(f"not reproducible: {expected}")
    if failures:
        raise SystemExit("\n".join(failures))


def remove_stale_outputs(output_dir: Path, releases: list[dict[str, str]]) -> None:
    keep = {
        str(Path(major_version(release["version"])) / f"{release['version']}.toml")
        for release in releases
    }
    for path in output_dir.rglob("*.toml"):
        if path.name == "manifest.toml":
            continue
        rel = path.relative_to(output_dir).as_posix()
        if rel not in keep:
            path.unlink()
    for path in sorted(output_dir.iterdir(), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--refresh-manifest", action="store_true")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--versions", nargs="*", help="versions to process")
    args = parser.parse_args(argv)

    if args.refresh_manifest:
        refresh_manifest(args.manifest)
    if not args.generate and not args.verify and not args.clean:
        return 0

    metadata, releases = load_manifest(args.manifest)
    selected = select_releases(releases, args.versions)
    if args.generate:
        for release in selected:
            output = generate_release(release, metadata, output_dir=args.output_dir, cache_dir=args.cache_dir)
            print(output.relative_to(ROOT))
    if args.clean:
        remove_stale_outputs(args.output_dir, releases)
    if args.verify:
        verify_outputs(selected, metadata, output_dir=args.output_dir, cache_dir=args.cache_dir)
        print("nvcc option metadata is reproducible")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
